---
title: "Part2_Statistics"
format: pdf
editor: visual
---

```{r}

library(corrr)
library(ggcorrplot)
library(FactoMineR)
library(vcd)
library(factoextra)
library(rfPermute)
library(ggfortify)
library(agricolae)
library(randomForest)
library(stats)
library(factoextra)
library(ade4)
library(magrittr)
```

Explorative Statistik:

Korrelogramme

```{r}

NDVI_allData<-do.call("rbind", list_NDVIavg_andNames)
PRI_allData<-do.call("rbind", list_PRIavg_andNames)
MCARI_allData<-do.call("rbind", list_MCARI1avg_andNmaes)
PSRI_allData<-do.call("rbind", list_PSRIavg_andNames)
QYMax_allData<-do.call("rbind", list_QY_max_andNames)       

Indices_allData<-NDVI_allData%>%mutate(variable=NULL)%>%rename(NDVI=value)%>%
          mutate(PRI=PRI_allData$value)%>%
          mutate(MCARI=MCARI_allData$value)%>%mutate(PSRI=PSRI_allData$value)%>%
          mutate(QYmax=QYMax_allData$value)%>%relocate(Condition, .after = Plant.Name.solo)
        
Indices_allData<-NDVI_allData%>%mutate(variable=NULL)%>%rename(NDVI=value)%>%
          mutate(PRI=PRI_allData$value)%>%mutate(MCARI=MCARI_allData$value)%>%
          mutate(PSRI=PSRI_allData$value)%>%mutate(QYmax=QYMax_allData$value)%>%
          relocate(Condition, .after = Plant.Name.solo)%>%relocate(NDVI, .after = Condition)
        
        
ggpairs(Indices_allData[,5:10], mapping=ggplot2::aes(colour=Condition),
                lower=list(continous=wrap("smooth", alpha=0.05, size=0.1)),
        diag = list(discrete="barDiag",continuous = wrap("densityDiag", alpha=0.5 )),
        cardinality_threshold = 40, title="Hyperspec Indices", legend=1)+
  theme(panel.grid.major = element_blank())+
  scale_color_manual(values = c("Control"="turquoise3", 
                                "Drought stress"="coral"))+
  scale_fill_manual(values = c("Control"="turquoise3", 
                                "Drought stress"="coral"))


#Bonitur data and Indices

ggpairs(Bonitur_Indices_all[,4:9], mapping=ggplot2::aes(colour=Treatment),
        lower=list(continous=wrap("smooth", alpha=0.05, size=0.1)),
        diag = list(discrete="barDiag",continuous = wrap("densityDiag", alpha=0.5 )),
        cardinality_threshold = 40, title="Hyperspec Indices", legend=1)+
    theme(panel.grid.major = element_blank())+
    scale_color_manual(values = c("irrigation"="turquoise3", 
                                  "drought stress"="coral"))+
    scale_fill_manual(values = c("irrigation"="turquoise3", 
                                 "drought stress"="coral"))
```

Histogramme:

```{r}
ggplot(PRI_allData, aes(x=value, color=Condition))+
   geom_histogram(aes(y=..density..), bins=20)+geom_density(alpha=0.2)+labs(title = "PRI DS vs. C")+scale_color_manual(values = c("Control"="turquoise3",
                                                                                                                                                                                  "Drought stress"="coral"))+
  scale_fill_manual(values = c("Control"="turquoise3",
                               "Drought stress"="coral"))



ggplot(NDVI_allData, aes(x=value, color=Condition))+
  geom_histogram(aes(y=..density..), bins=20)+geom_density(alpha=0.2)+labs(title = "NDVI DS vs. C")+scale_color_manual(values = c("Control"="turquoise3",
                                                                                                                                                                                    "Drought stress"="coral"))+
  scale_fill_manual(values = c("Control"="turquoise3",
                               "Drought stress"="coral"))



ggplot(MCARI_allData, aes(x=value, color=Condition))+geom_histogram(aes(y=..density..), bins=20)+
  geom_density(alpha=0.2)+labs(title = "MCARI DS vs. C")+scale_color_manual(values = c("Control"="turquoise3",
                                                                                                                                                                                      "Drought stress"="coral"))+
  scale_fill_manual(values = c("Control"="turquoise3",
                               "Drought stress"="coral"))

```



lineare Regression:

```{r}

allData_IndicesBOnitur<-Bonitur_Indices_all

lm_IndicesLeaf_plus<-lm(LeafNumber~NDVI+MCARI+PRI, data=allData_IndicesBOnitur)
lm_IndicesLeaf_mix1<-lm(LeafNumber~NDVI*MCARI+PRI, data=allData_IndicesBOnitur)
lm_IndicesLeaf_mix2<-lm(LeafNumber~NDVI+MCARI*PRI, data=allData_IndicesBOnitur)
lm_IndicesLeaf_mal<-lm(LeafNumber~NDVI*MCARI*PRI, data=allData_IndicesBOnitur)

lm_TillerIndices_plus<-lm(TillerNumber~NDVI+MCARI+PRI, data=allData_IndicesBOnitur)
lm_TillerIndices_mix1<-lm(TillerNumber~NDVI*MCARI+PRI, data=allData_IndicesBOnitur)
lm_TillerIndices_mix2<-lm(TillerNumber~NDVI+MCARI*PRI, data=allData_IndicesBOnitur)
lm_TillerIndices_mal<-lm(TillerNumber~NDVI*MCARI*PRI, data=allData_IndicesBOnitur)

AIC(lm_TillerIndices_mal, lm_TillerIndices_mix1, lm_TillerIndices_mix2, lm_TillerIndices_plus)
#"                      df      AIC
#lm_TillerIndices_mal   9 3055.003
#lm_TillerIndices_mix1  6 3114.636
#lm_TillerIndices_mix2  6 3133.963
#lm_TillerIndices_plus  5 3133.803"

AIC(lm_IndicesLeaf_mal, lm_IndicesLeaf_mix1, lm_IndicesLeaf_mix2, lm_IndicesLeaf_plus)
#"                    df      AIC
#lm_IndicesLeaf_mal   9 1306.064
#lm_IndicesLeaf_mix1  6 1307.670
#lm_IndicesLeaf_mix2  6 1306.591
#lm_IndicesLeaf_plus  5 1306.520"


plot(lm_TillerIndices_plus)

#predicted vs. observed for Leafnumber:

x<-predict(lm_IndicesLeaf_plus)
plot(x, allData_IndicesBOnitur$LeafNumber)
abline(a=0, b=1)

```

PCAs und MF Anova

```{r}

###MF Anova mit allen Zeitdaten:

model_allData_TN<-aov(TillerNumber~Genotype, data=Bonitur_Indices_all)
anova_model_allData_TN<-Anova(model_allData_TN, type="III")

anova_model_allData_TN
#"Anova Table (Type III tests)
#
#Response: TillerNumber
#Sum Sq  Df F value    Pr(>F)    
#(Intercept)   710.5   1 27.9459 1.769e-07 ***
#  Genotype      798.0  19  1.6519   0.04027 *  
#  Residuals   14746.7 580                      
#---
#  Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1"


posthoc_genotype = emmeans(model_allData_TN, ~Genotype, adjust="tukey", na.action = na.exclude)
posthoc_result_genotype <- cld(posthoc_genotype, alpha=0.05, Letter=letters, adjust="tukey")
posthoc_result_genotype



#PCA mit allen Zeitdatebn


fuck.pca_NDVIall_TN<-PCA(dplyr::select(Bonitur_Indices_all, NDVI, TillerNumber), scale.unit=TRUE, graph=TRUE)
fviz_pca_ind(fuck.pca_NDVIall_TN, label="none", col.ind = Bonitur_Indices_all$Treatment, 
             addEllipses = TRUE, ellipse.level=0.95,
             palette=c("lightgreen", "magenta"), ellipse.type="convex",title="PCA - individuals NDVI all dates")




#####PCA mit allen Zeit- und allen Indexdaten:


fuck.pca_allIndices_allBoni<-PCA(dplyr::select(Bonitur_Indices_all, LeafNumber, TillerNumber,NDVI, MCARI, PRI), scale.unit=TRUE, graph=TRUE)
fviz_pca_ind(fuck.pca_NDVIall_TN, label="none", col.ind = Bonitur_Indices_all$Treatment, 
             addEllipses = TRUE, ellipse.level=0.95,
             palette=c("lightgreen", "magenta"), ellipse.type="convex",title="PCA - individuals all dates, all data")

```

Drone data wrangling and comparison with Growth CHamber data:

```{r}

lorenzos_drone_data<-read.csv("C:/Users/HabisohnC/Desktop/WhaetVIZ_metadata/ndvis.csv",
                              header=FALSE)

colnames(lorenzos_drone_data)<-c("Date", "Plotnumber", "NDVI_raw")

master_zuordnung_droneData<-read_excel("C:/Users/HabisohnC/Desktop/WhaetVIZ_metadata/WheatVIZ_FieldExperiments2024_Measurements_20231219.xlsx")

master_zuordnung_DroneData_slim<-master_zuordnung_droneData%>%dplyr::select(Plot,Name)
master_zuordnung_DroneData_slim<-master_zuordnung_DroneData_slim[-1,]
master_zuordnung_DroneData_slim<-master_zuordnung_DroneData_slim[-1,]



iwillfindyou2<-subset(master_zuordnung_DroneData_slim, Name %in% unique(metatable$Plant.Name.solo))

colnames(iwillfindyou2)<-c("Plotnumber","Genotype")

dronedata_genotype_assigned<-inner_join(iwillfindyou2,
                                        lorenzos_drone_data, by="Plotnumber")
unique(dronedata_genotype_assigned$Genotype)



normalized_droneData_assigned<-dronedata_genotype_assigned%>%
  mutate(NDVI.norm=NDVI_raw/255)%>%relocate(Date)

sd_mean_normalized_droneData<-normalized_droneData_assigned%>%group_by(Date, Genotype)%>%
  summarise(Mean=mean(NDVI.norm), SD=sd(NDVI.norm))

sd_mean_normalized_droneData_nolows<-sd_mean_normalized_droneData%>%filter(Date!="2023-05-15")

#growth chamber plots
control_plantsOnlyNDVI<-select_condition(list_mean_sd_NDVI, "Control")%>%bind_rows()%>%drop_na()

ggplot(control_plantsOnlyNDVI, aes(x=as.Date(Measuring.Date, format="%Y-%m-%d"), y=Mean,group=Name, color=Name))+
  xlab("Date")+labs(title="NDVI Control Plants")+geom_line()+scale_color_manual(values=mycolors)+ylim(0.60,0.95)+
  theme_bw(base_size = 10)+
  theme(axis.text.x = element_text(angle=75, hjust=1.2),plot.title = element_text(size=16), 
        legend.text=element_text(size=9),legend.title = element_text(size=13),
        axis.text=element_text(size=13),axis.title=element_text(size=14))+
  guides(color=guide_legend(override.aes=list(linewidth=5)))


######

#plot drone data no 15.05.2023 (low values due to cloudy weather conditions, possibly)

ggplot(sd_mean_normalized_droneData_nolows, aes(x=as.Date(Date, format="%Y-%m-%d"), y=Mean,group=Genotype, color=Genotype))+
  xlab("Date")+labs(title="NDVI Drone Data 2023")+geom_line()+scale_color_manual(values=mycolors)+ylim(0.60,0.95)+
  theme_bw(base_size = 10)+
  theme(axis.text.x = element_text(angle=75, hjust=1.2),plot.title = element_text(size=16), 
        legend.text=element_text(size=9),legend.title = element_text(size=13),
        axis.text=element_text(size=13),axis.title=element_text(size=14))+
  guides(color=guide_legend(override.aes=list(linewidth=5)))



######barplot Drone data vs growth chamber data

droneData_24052023_NDVImean<-sd_mean_normalized_droneData%>%filter(Date=="2023-05-24")
growthChamber_28022024_NDVImean<-bind_rows(list_mean_sd_NDVI)%>%filter(Measuring.Date=="2024-02-28", 
                                                                       Condition=="Control")

growthChamber_28022024_NDVImean<-growthChamber_28022024_NDVImean%>%rename(Genotype=Name)
growthChamber_28022024_NDVImean<-growthChamber_28022024_NDVImean[order(growthChamber_28022024_NDVImean$Mean, decreasing = TRUE),]

all_NDVI_barplot<-rbind(within(droneData_24052023_NDVImean, {DS<-'DD'}),
                        within(growthChamber_28022024_NDVImean, {DS<-'GC'}))
all_NDVI_barplot<-all_NDVI_barplot[,-1]
all_NDVI_barplot<-all_NDVI_barplot[,-6]
all_NDVI_barplot<-all_NDVI_barplot[,-5]



#combined_DD_GC_NDVI_singleDay<-droneData_24052023_NDVImean%>%inner_join(growthChamber_28022024_NDVImean, by="Genotype")



ggplot(all_NDVI_barplot, aes(x=Genotype, y=Mean, fill=Mean, group=DS))+
  geom_col(position="dodge", color="turquoise")+coord_cartesian(ylim=c(0.65,0.95))+
  geom_text(aes(label=DS), vjust=1.5, position=position_dodge(.9), colour="white")+
  theme(axis.text.x = element_text(angle=75, hjust=1.2))

ggplot(all_NDVI_barplot, aes(x=reorder(Genotype, +Mean), y=Mean, fill=Mean, group=DS))+
  geom_bar(stat="identity",position="dodge", color="turquoise")+coord_cartesian(ylim=c(0.65,0.95))+
  geom_text(aes(label=DS), vjust=1.5, position=position_dodge(.9), colour="white")+
  theme(axis.text.x = element_text(angle=75, hjust=1.2))
```


```{r}

ggplot(NDVI_allDates, aes(x=as.Date(Measuring.Date, format="%Y-%m-%d"), y=value, color=Condition))+
    ylab("NDVI average")+xlab("Date")+labs(title="NDVI all Genotypes")+
    geom_point()+geom_rect(aes(xmin=as.Date("2024-02-12", format="%Y-%m-%d"),xmax=as.Date("2024-03-01", format="%Y-%m-%d"),ymin=-Inf,ymax=Inf),alpha=0.02,fill="lightgrey", color="lightgrey")+theme_bw(base_size = 10)+
    scale_color_manual(values = c("Control"="turquoise3", 
                                  "Drought stress"="coral"))+
    theme(axis.text.x = element_text(angle=90, vjust=0.5, size=9))+
    geom_smooth(method="lm",aes(color=Condition, group=Condition))+geom_point()

lm_NDVI<-lm(value~Measuring.Date, data=NDVI_allDates)

summary(lm_NDVI)

plot(lm_NDVI)

```

```{r}

#BLUES and BLUPS:

#-> define which model underlying
